[line_break]
disabled = true

[package]
disabled = true

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[](bold white) "

[cmd_duration]
disabled = true

[username]
format = "[$user]($style)"

[hostname]
ssh_only = true
format =  "@[$hostname]($style) "
