use_nerdfont = true
flip_status_indicators = true

[keybindings]
"q" = "back"
"d" = "move down 5"
"u" = "move up 5"
"g" = "move top"
"Shift+g" = "move bottom"
"Shift+d" = "delete"
"Shift+q" = "quit"

[theme]
title = "blue"
playing_selected = "light blue"
playing = "blue"
highlight = "light white"
highlight_bg = "#333640"
error = "light white"
error_bg = "red"
cmdline = "light white"
cmdline_bg = "black"
search_match = "light red"
