use_nerdfont = true
flip_status_indicators = true

[theme]
title = "blue"
playing_selected = "light blue"
playing = "blue"
highlight = "light white"
highlight_bg = "#333640"
error = "light white"
error_bg = "red"
cmdline = "light white"
cmdline_bg = "black"
search_match = "light red"
